language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ree
env:
  - MATRIX_LIBRARY=gsl
  - MATRIX_LIBRARY=narray
  - MATRIX_LIBRARY=nmatrix
  - MATRIX_LIBRARY=matrix
matrix:
  exclude:
    - rvm: 1.8.7
      env: MATRIX_LIBRARY=nmatrix
    - rvm: ree
      env: MATRIX_LIBRARY=nmatrix
# http://stackoverflow.com/a/12029573/244258
before_install:
  - curl -O http://mirror.veriportal.com/gnu/gsl/gsl-1.14.tar.gz
  - tar xvzf gsl-1.14.tar.gz
  - cd gsl-1.14
  - ./configure
  - make
  - sudo make install
  - rvm rubygems 1.8.25
