language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ree
env:
  - MATRIX_LIBRARY=gsl
  - MATRIX_LIBRARY=narray
  - MATRIX_LIBRARY=matrix
before_install:
  - if [ $MATRIX_LIBRARY = 'gsl' ]; then sudo apt-get install gsl-bin libgsl0-dev; fi
  - bundle config build.nmatrix --with-lapacklib
# Travis sometimes runs without Bundler.
install: bundle
script: bundle exec rake --trace
