language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ree
env:
  - MATRIX_LIBRARY=gsl
  - MATRIX_LIBRARY=narray
  - MATRIX_LIBRARY=nmatrix
  - MATRIX_LIBRARY=matrix
matrix:
  exclude:
    - rvm: 1.8.7
      env: MATRIX_LIBRARY=nmatrix
    - rvm: ree
      env: MATRIX_LIBRARY=nmatrix
before_install:
  # https://github.com/SciRuby/nmatrix/wiki/Installation
  # @note If installing libatlas-base-dev libatlas3gf-base via apt-get,
  # /usr/lib/libcblas.so and /usr/lib/libatlas.so will already exist.
  - sudo apt-get update -qq -y
  - sudo apt-get install -qq -y libblas3gf libblas-dev gfortran

  - curl -o atlas3.10.1.tar.bz2 "http://downloads.sourceforge.net/project/math-atlas/Stable/3.10.1/atlas3.10.1.tar.bz2?r=&ts=1367178352&use_mirror=iweb"
  - curl -O http://www.netlib.org/lapack/lapack-3.4.2.tgz

  # http://www.vesperix.com/arm/atlas-arm/faq/index.html
  # @note Travis does not have those `cpu` directories.

  # http://math-atlas.sourceforge.net/atlas_install/node6.html
  # http://math-atlas.sourceforge.net/atlas_install/node8.html
  - bunzip2 -c atlas3.10.1.tar.bz2 | tar xfm -
  - cd ATLAS
  - ./configure -b 32 --with-netlib-lapack-tarfile=$HOME/lapack-3.4.1.tgz
  - make build
  - sudo make install

  # http://stackoverflow.com/a/12029573/244258
  - curl -O http://mirror.veriportal.com/gnu/gsl/gsl-1.14.tar.gz
  - tar xzf gsl-1.14.tar.gz
  - cd gsl-1.14
  - ./configure
  - make
  - sudo make install

  # http://stackoverflow.com/a/15910419/244258
  - rvm rubygems 1.8.25
  - bundle
script:
  - bundle exec rake --trace
