language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ree
env:
  - MATRIX_LIBRARY=gsl
  - MATRIX_LIBRARY=narray
  - MATRIX_LIBRARY=nmatrix
  - MATRIX_LIBRARY=matrix
matrix:
  exclude:
    - rvm: 1.8.7
      env: MATRIX_LIBRARY=nmatrix
    - rvm: ree
      env: MATRIX_LIBRARY=nmatrix
# http://about.travis-ci.org/docs/user/build-configuration/
# http://about.travis-ci.org/docs/user/ci-environment/
# http://about.travis-ci.org/docs/user/languages/ruby/
before_install:
  # http://sciruby.com/docs/installation/atlas.html
  # If installing libatlas-base-dev libatlas3gf-base via apt-get,
  # /usr/lib/libcblas.so and /usr/lib/libatlas.so will already exist.
  # In any case, installing ATLAS with apt-get causes errors.
  # @see https://gist.github.com/jpmckinney/2eedb9a22eb47bfe9966

  # @todo Is it possible to turn off CPU throttling on Travis?
  # http://www.scipy.org/Installing_SciPy/Linux#head-82f9b2311041a8bda03b77e831b5b932e3be4f82
  # http://www.vesperix.com/arm/atlas-arm/faq/index.html
  # Travis does not have those `/sys/devices/system/cpu/` directories.

  # http://ubuntuforums.org/showthread.php?t=1325671
  # http://ubuntuforums.org/showthread.php?t=1877944
  - if [ $MATRIX_LIBRARY = 'nmatrix' ]; then sudo apt-get update -qq; fi
  - if [ $MATRIX_LIBRARY = 'nmatrix' ]; then sudo apt-get install -qq libblas3gf libblas-dev gfortran-multilib gfortran libc6-dev-i386 > /dev/null; fi
  # http://math-atlas.sourceforge.net/atlas_install/node6.html
  - if [ $MATRIX_LIBRARY = 'nmatrix' ]; then curl -s -o $HOME/lapack-3.4.2.tgz http://www.netlib.org/lapack/lapack-3.4.2.tgz; fi
  - if [ $MATRIX_LIBRARY = 'nmatrix' ]; then curl -s -L -O http://downloads.sourceforge.net/project/math-atlas/Stable/3.10.1/atlas3.10.1.tar.bz2; fi
  - if [ $MATRIX_LIBRARY = 'nmatrix' ]; then bunzip2 -c atlas3.10.1.tar.bz2 | tar xfm -; fi
  - if [ $MATRIX_LIBRARY = 'nmatrix' ]; then cd ATLAS; fi
  # ATLAS will complain if you do not build in a subdirectory.
  - if [ $MATRIX_LIBRARY = 'nmatrix' ]; then mkdir subdir; fi
  - if [ $MATRIX_LIBRARY = 'nmatrix' ]; then cd subdir; fi
  # https://github.com/vtjnash/atlas-3.10.0/blob/master/INSTALL.txt
  # http://math-atlas.sourceforge.net/atlas_install/node8.html
  - if [ $MATRIX_LIBRARY = 'nmatrix' ]; then ../configure -b 32 -D c -DWALL --with-netlib-lapack-tarfile=$HOME/lapack-3.4.2.tgz; fi
  # If we add `> /dev/null`, Travis fails with: "No output has been received in
  # the last 10 minutes, this potentially indicates a stalled build or something
  # wrong with the build itself." If we don't add it, Travis will sometimes
  # terminate, because the log file is too long.
  - if [ $MATRIX_LIBRARY = 'nmatrix' ]; then make build; fi
  - if [ $MATRIX_LIBRARY = 'nmatrix' ]; then sudo make install; fi

  - if [ $MATRIX_LIBRARY = 'gsl' ]; then sudo apt-get install gsl-bin libgsl0-dev; fi
# Travis sometimes runs without Bundler.
install: bundle
script: bundle exec rake --trace
